DEFAULT_CONN_TYPE = "ap"
DEFAULT_PROTO_TYPE = "udp"

ROBOT_SDK_PORT_MIN = 10100
ROBOT_SDK_PORT_MAX = 10500

ENV_ROBOT_PORT = 5000
ENV_ROBOT_DEFAULT_ADDR= ('localhost', ENV_ROBOT_PORT)

ROBOT_DEFAULT_LOCAL_WIFI_ADDR = ('localhost', ROBOT_SDK_PORT_MIN)